# Generated by Django 4.2.9 on 2024-08-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cover', models.ImageField(blank=True, default='random.jpg', null=True, upload_to='covers/products')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-id', '-updated'],
            },
        ),
        migrations.AlterField(
            model_name='categories',
            name='cover',
            field=models.ImageField(blank=True, default='random.jpg', null=True, upload_to='covers/categories'),
        ),
    ]
