# Generated by Django 4.2.9 on 2024-08-29 12:43

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_products_alter_categories_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[base.models.validate_non_negative]),
        ),
    ]
