# Generated by Django 4.2.9 on 2024-08-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='height',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='tags',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='width',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
